version: '2'
services:
  PostgreSQL:
    container_name: postgresql
    restart: always
    image: 'postgres:9.6'
    environment:
      - DEBUG=false
      - DB_USER=hppoc
      - DB_PASS=password
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - './data/peerdata/pssql:/var/lib/postgresql'
      - './data/peerdata/db:/app/db/'
      - './db/explorerpg.sql:/docker-entrypoint-initdb.d/1-schema.sql'
      - './db/updatepg.sql:/docker-entrypoint-initdb.d/2-data.sql'
    networks:
      - byfn-test
  explorer:
    restart: always
    build: "./explorer/."
    environment:
      - >-
        CHANNELS=chus-east-1-n6onyyrtm-e18f32b0-5c94-41fa-91f4-bb983f147833:My
        Xooa Ledger
      - ORG=test
      - PEER_NAME=peer.test.external.xooa.com
      - ORDERER=orderer2.orderers.cluster1.aws.xooa.com
      - TLS_ENABLED=false
      - DATABASE_HOST=postgresql
    ports:
      - '8080:8080'
      - '3000:3000'
    volumes:
      - './crypto-config:/crypto-config/'
      - '/home/tft/Test-xooa/explorer/client:/opt/explorer/client'
    networks:
      - byfn-test
    depends_on:
      - PostgreSQL
      - peer.test.external.xooa.com
    command: ["node", "explorer/configure.js", "&&", "tail", "-f","/dev/null;","/bin/sh", "-c", "cd","explorer/client","&&","npm", "start"]   
  
  peer.test.external.xooa.com:
    image: hyperledger/fabric-peer
    container_name: peer.test.external.xooa.com
    environment:
      - CORE_PEER_ID=peer.test.external.xooa.com
      - CORE_PEER_LOCALMSPID=test
      - CORE_CHAINCODE_LOGGING_SHIM=DEBUG
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=byfn-test
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=false
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.test.external.xooa.com:7051'
    command: peer node start
    volumes:
      - >-
        ./crypto-config/peerOrganizations/org.test.com/peers/peer0.org.test.com/:/etc/hyperledger/crypto/peer
      - './data/peerdata:/var/hyperledger'
    networks:
      - byfn-test
networks:
  byfn-test: null
